debug: false
#management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.project-board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: sol
    password: 1111
#    driver-class-name:

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
  sql:
      init:
        mode: always

---

spring:
  profiles:
    active: testdb
#  datasource:
#    url: jdbc:h2:mem:bord;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
